
influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8086:8086"
    - "2003:2003"
    - "8083:8083"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    - ./influxdb.conf:/etc/influxdb/influxdb.conf 
    - /srv/docker/influxdb/data:/tmp/influxdb/data
    
grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3030"
  env_file:
    - 'env.grafana'
  links:
    - influxdb
  volumes:
    - ./grafana.ini:/etc/grafana/grafana.ini
    - /srv/docker/grafana/data:/tmp/grafana
    
nginx:
  image: nginx:latest
  container_name: nginx
  ports:
    - "80:80"
  links:
    - grafana
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf 
    
telegraf:
  image: telegraf:latest
  container_name: telegraf
  links:
    - influxdb
  volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf
    - /var/run/docker.sock:/var/run/docker.sock
    